# Generated by Django 4.0.3 on 2022-04-03 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0003_alter_academicform_time_spend'),
    ]

    operations = [
        migrations.CreateModel(
            name='Academic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('batch', models.CharField(choices=[('018', '018'), ('017', '017'), ('016', '016'), ('015', '015')], max_length=10)),
                ('specialty', models.CharField(choices=[('GIS/RM', 'GIS/RM'), ('Geodisy', 'Geodisy'), ('Photogrammetry', 'Photogrammetry')], max_length=20)),
                ('index', models.IntegerField()),
                ('time', models.CharField(choices=[('ساعتان في الاسبوع', 'ساعتان في الاسبوع'), ('ثلاث ساعات في الاسبوع', 'ثلاث ساعات في الاسبوع'), ('اكثر من ثلات ساعات', 'اكثر من ثلات ساعات')], max_length=50)),
                ('notes', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='AcademicForm',
        ),
    ]
